# Generated by Django 6.0.5 on 2026-05-27 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auto_flagged', 'Auto-Flagged by System'), ('flagged', 'Flagged by Analyst'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Values Edited'), ('locked', 'Locked for Audit'), ('unlocked', 'Unlocked for Correction'), ('commented', 'Comment Added')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text='{field: {old, new}}')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='ingestion.normalizedemission')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'review_actions',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ingestion.normalizedemission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'review_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
