# Generated by Django 6.0.5 on 2026-05-27 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ingestion', 'Data Ingestion'), ('normalization', 'Normalization'), ('review', 'Review Action'), ('edit', 'Data Edit'), ('lock', 'Lock for Audit'), ('unlock', 'Unlock for Correction'), ('export', 'Data Export'), ('login', 'User Login'), ('config_change', 'Configuration Change')], max_length=20)),
                ('action_detail', models.CharField(help_text='Human-readable description', max_length=255)),
                ('record_type', models.CharField(help_text='Model name: NormalizedEmission, RawSAPRecord, etc.', max_length=50)),
                ('record_id', models.CharField(help_text='UUID of the affected record', max_length=36)),
                ('before_data', models.JSONField(blank=True, help_text='State before the action', null=True)),
                ('after_data', models.JSONField(blank=True, help_text='State after the action', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'action_type'], name='audit_logs_tenant__0c06d1_idx'), models.Index(fields=['record_type', 'record_id'], name='audit_logs_record__7a6c03_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
